# Generated by Django 6.0.1 on 2026-01-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_marks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
