# Generated by Django 6.0.1 on 2026-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='max_marks',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
